engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: false
engines:
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
  - "**.js"
  - "**.ts"
  - "**.html"
  - "**.css"
