version: "2"

services:
  ui:
    build: ./ui
    working_dir: /srv/app
    entrypoint:
        - "ng"
        - "serve"
        - "--environment=dev"
        - "--host=0.0.0.0"
        - "--port=5000"
    restart: on-failure
    volumes:
      - ./ui:/srv/app:z
      - ui_node_modules:/srv/app/node_modules
    ports:
      - "5000:5000"
  api:
    depends_on:
      - mongodb
    build: .
    working_dir: /srv/www
    entrypoint:
        - python
        - server.py
    restart: on-failure
    volumes:
      - ./src:/srv/www:z
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://democraticcollaboration_mongodb_1:27017
      - TOKEN=${TOKEN}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - DEBUG=true

  mongodb:
    image: mongo:3.4.6

volumes:
  ui_node_modules:
