version: 2
jobs:
    test:
      docker:
        - image: circleci/python:3.7-stretch-node
        - image: circleci/mongo:latest
      steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: npm install
      - run: npm test
      - run: npm run build
      - run: pycodestyle
      - run: pytest --cov=src --cov-report xml
      - run: python-codacy-coverage -r coverage.xml
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
